DROP DATABASE IF EXISTS TODODB;
CREATE DATABASE TODODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

-- ---
-- Globals
-- ---

-- SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
-- SET FOREIGN_KEY_CHECKS=0;

-- ---
-- Table 'TODODB.USER_LIST'
-- ユーザー情報
-- ---

DROP TABLE IF EXISTS TODODB.USER_LIST;
		
CREATE TABLE TODODB.USER_LIST (
  userID INTEGER NOT NULL AUTO_INCREMENT,
  passwd VARCHAR(100) NOT NULL,
  PRIMARY KEY (userID)
) COMMENT 'ユーザー情報';

-- ---
-- Table 'TODODB.WORD_LIST'
-- TODOの文から登録された単語
-- ---

DROP TABLE IF EXISTS TODODB.WORD_LIST;
		
CREATE TABLE TODODB.WORD_LIST (
  wordID INTEGER NOT NULL AUTO_INCREMENT,
  word VARCHAR(200) NOT NULL,
  type VARCHAR(20) NULL DEFAULT NULL,
  sentenceID INTEGER NOT NULL,
  userID INTEGER NOT NULL,
  PRIMARY KEY (wordID)
) COMMENT 'TODOの文から登録された単語';

-- ---
-- Table 'TODODB.SENTENCE_LIST'
-- TODOの文
-- ---

DROP TABLE IF EXISTS TODODB.SENTENCE_LIST;
		
CREATE TABLE TODODB.SENTENCE_LIST (
  sentenceID INTEGER NOT NULL AUTO_INCREMENT,
  todo VARCHAR(200) NOT NULL,
  creation_date DATE NOT NULL DEFAULT '000000',
  deadline DATE NULL,
  finished ENUM('false', 'true') NOT NULL,
  userID INTEGER NOT NULL,
  PRIMARY KEY (sentenceID)
) COMMENT 'TODOの文';

-- ---
-- Foreign Keys 
-- ---

ALTER TABLE TODODB.WORD_LIST ADD FOREIGN KEY (sentenceID) REFERENCES TODODB.SENTENCE_LIST (sentenceID);
ALTER TABLE TODODB.WORD_LIST ADD FOREIGN KEY (userID) REFERENCES TODODB.USER_LIST (userID);
ALTER TABLE TODODB.SENTENCE_LIST ADD FOREIGN KEY (userID) REFERENCES TODODB.USER_LIST (userID);

-- ---
-- Table Properties
-- ---

-- ALTER TABLE TODODB.USER_LIST ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE TODODB.WORD_LIST ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE TODODB.SENTENCE_LIST ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ---
-- Test Data
-- ---

-- INSERT INTO TODODB.USER_LIST (userID,passwd) VALUES
-- ('','');
-- INSERT INTO TODODB.WORD_LIST (wordID,word,type,sentenceID,userID) VALUES
-- ('','','','','');
-- INSERT INTO TODODB.SENTENCE_LIST (sentenceID,todo,creation_date,deadline,finished,userID) VALUES
-- ('','','','','','');



INSERT INTO TODODB.USER_LIST(userid, passwd) VALUES("SCI01449", "DBPW#0511loki");
